"""empty message

Revision ID: 5685776b741c
Revises: c006e8463eb4
Create Date: 2024-04-16 22:04:45.146233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5685776b741c'
down_revision = 'c006e8463eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
